apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  rhtap/gitops: codegen3-may5-1
  janus-idp.io/tekton: codegen3-may5-1
  backstage.io/kubernetes-id: codegen3-may5-1
  backstage.io/kubernetes-namespace: codegen3-may5-1
  app.kubernetes.io/part-of: codegen3-may5-1
resources:
  - application-dev.yaml